using System.Collections.Generic;

namespace WebFormsCore.UI
{
    public enum HtmlTextWriterAttribute
    {
        Accesskey = 0,
        Align = 1,
        Alt = 2,
        Background = 3,
        Bgcolor = 4,
        Border = 5,
        Bordercolor = 6,
        Cellpadding = 7,
        Cellspacing = 8,
        Checked = 9,
        Class = 10,
        Cols = 11,
        Colspan = 12,
        Disabled = 13,
        For = 14,
        Height = 15,
        Href = 16,
        Id = 17,
        Maxlength = 18,
        Multiple = 19,
        Name = 20,
        Nowrap = 21,
        Onchange = 22,
        Onclick = 23,
        ReadOnly = 24,
        Rows = 25,
        Rowspan = 26,
        Rules = 27,
        Selected = 28,
        Size = 29,
        Src = 30,
        Style = 31,
        Tabindex = 32,
        Target = 33,
        Title = 34,
        Type = 35,
        Valign = 36,
        Value = 37,
        Width = 38,
        Wrap = 39,
        Abbr = 40,
        AutoComplete = 41,
        Axis = 42,
        Content = 43,
        Coords = 44,
        DesignerRegion = 45,
        Dir = 46,
        Headers = 47,
        Longdesc = 48,
        Rel = 49,
        Scope = 50,
        Shape = 51,
        Usemap = 52,
        VCardName = 53
    }

    public static class HtmlTextWriterAttributeExtensions
    {
        static Dictionary<HtmlTextWriterAttribute, string> s_attributes = new Dictionary<HtmlTextWriterAttribute, string>
        {
            { HtmlTextWriterAttribute.Accesskey, "accesskey" },
            { HtmlTextWriterAttribute.Align, "align" },
            { HtmlTextWriterAttribute.Alt, "alt" },
            { HtmlTextWriterAttribute.Background, "background" },
            { HtmlTextWriterAttribute.Bgcolor, "bgcolor" },
            { HtmlTextWriterAttribute.Border, "border" },
            { HtmlTextWriterAttribute.Bordercolor, "bordercolor" },
            { HtmlTextWriterAttribute.Cellpadding, "cellpadding" },
            { HtmlTextWriterAttribute.Cellspacing, "cellspacing" },
            { HtmlTextWriterAttribute.Checked, "checked" },
            { HtmlTextWriterAttribute.Class, "class" },
            { HtmlTextWriterAttribute.Cols, "cols" },
            { HtmlTextWriterAttribute.Colspan, "colspan" },
            { HtmlTextWriterAttribute.Disabled, "disabled" },
            { HtmlTextWriterAttribute.For, "for" },
            { HtmlTextWriterAttribute.Height, "height" },
            { HtmlTextWriterAttribute.Href, "href" },
            { HtmlTextWriterAttribute.Id, "id" },
            { HtmlTextWriterAttribute.Maxlength, "maxlength" },
            { HtmlTextWriterAttribute.Multiple, "multiple" },
            { HtmlTextWriterAttribute.Name, "name" },
            { HtmlTextWriterAttribute.Nowrap, "nowrap" },
            { HtmlTextWriterAttribute.Onchange, "onchange" },
            { HtmlTextWriterAttribute.Onclick, "onclick" },
            { HtmlTextWriterAttribute.ReadOnly, "readonly" },
            { HtmlTextWriterAttribute.Rows, "rows" },
            { HtmlTextWriterAttribute.Rowspan, "rowspan" },
            { HtmlTextWriterAttribute.Rules, "rules" },
            { HtmlTextWriterAttribute.Selected, "selected" },
            { HtmlTextWriterAttribute.Size, "size" },
            { HtmlTextWriterAttribute.Src, "src" },
            { HtmlTextWriterAttribute.Style, "style" },
            { HtmlTextWriterAttribute.Tabindex, "tabindex" },
            { HtmlTextWriterAttribute.Target, "target" },
            { HtmlTextWriterAttribute.Title, "title" },
            { HtmlTextWriterAttribute.Type, "type" },
            { HtmlTextWriterAttribute.Valign, "valign" },
            { HtmlTextWriterAttribute.Value, "value" },
            { HtmlTextWriterAttribute.Width, "width" },
            { HtmlTextWriterAttribute.Wrap, "wrap" },
            { HtmlTextWriterAttribute.Abbr, "abbr" },
            { HtmlTextWriterAttribute.AutoComplete, "autocomplete" },
            { HtmlTextWriterAttribute.Axis, "axis" },
            { HtmlTextWriterAttribute.Content, "content" },
            { HtmlTextWriterAttribute.Coords, "coords" },
            { HtmlTextWriterAttribute.DesignerRegion, "designerregion" },
            { HtmlTextWriterAttribute.Dir, "dir" },
            { HtmlTextWriterAttribute.Headers, "headers" },
            { HtmlTextWriterAttribute.Longdesc, "longdesc" },
            { HtmlTextWriterAttribute.Rel, "rel" },
            { HtmlTextWriterAttribute.Scope, "scope" },
            { HtmlTextWriterAttribute.Shape, "shape" },
            { HtmlTextWriterAttribute.Usemap, "usemap" },
            { HtmlTextWriterAttribute.VCardName, "vcardname" },
        };

        public static string ToName(this HtmlTextWriterAttribute attribute) => s_attributes[attribute];
    }
}
