using System.Collections.Generic;

namespace WebFormsCore.UI
{
    public enum HtmlTextWriterStyle
    {
        BackgroundColor = 0,
        BackgroundImage = 1,
        BorderCollapse = 2,
        BorderColor = 3,
        BorderStyle = 4,
        BorderWidth = 5,
        Color = 6,
        FontFamily = 7,
        FontSize = 8,
        FontStyle = 9,
        FontWeight = 10,
        Height = 11,
        TextDecoration = 12,
        Width = 13,
        ListStyleImage = 14,
        ListStyleType = 15,
        Cursor = 16,
        Direction = 17,
        Display = 18,
        Filter = 19,
        FontVariant = 20,
        Left = 21,
        Margin = 22,
        MarginBottom = 23,
        MarginLeft = 24,
        MarginRight = 25,
        MarginTop = 26,
        Overflow = 27,
        OverflowX = 28,
        OverflowY = 29,
        Padding = 30,
        PaddingBottom = 31,
        PaddingLeft = 32,
        PaddingRight = 33,
        PaddingTop = 34,
        Position = 35,
        TextAlign = 36,
        VerticalAlign = 37,
        TextOverflow = 38,
        Top = 39,
        Visibility = 40,
        WhiteSpace = 41,
        ZIndex = 42
    }

    public static class HtmlTextWriterStyleExtensions
    {
        static Dictionary<HtmlTextWriterStyle, string> s_attributes = new Dictionary<HtmlTextWriterStyle, string>
        {
            {HtmlTextWriterStyle.BackgroundColor, "Background-Color" },
            {HtmlTextWriterStyle.BackgroundImage, "Background-Image" },
            {HtmlTextWriterStyle.BorderCollapse, "BorderCollapse" },
            {HtmlTextWriterStyle.BorderColor, "Border-Color" },
            {HtmlTextWriterStyle.BorderStyle, "Border-Style" },
            {HtmlTextWriterStyle.BorderWidth, "Border-Width" },
            {HtmlTextWriterStyle.Color, "Color" },
            {HtmlTextWriterStyle.Cursor, "Cursor" },
            {HtmlTextWriterStyle.Direction, "Direction" },
            {HtmlTextWriterStyle.Display, "Display" },
            {HtmlTextWriterStyle.Filter, "Filter" },
            {HtmlTextWriterStyle.FontFamily, "Font-Family" },
            {HtmlTextWriterStyle.FontSize, "Font-Size" },
            {HtmlTextWriterStyle.FontStyle, "Font-Style" },
            {HtmlTextWriterStyle.FontVariant, "Font-Variant" },
            {HtmlTextWriterStyle.FontWeight, "Font-Weight" },
            {HtmlTextWriterStyle.Height, "Height" },
            {HtmlTextWriterStyle.Left, "Left" },
            {HtmlTextWriterStyle.ListStyleImage, "List-Style-Image" },
            {HtmlTextWriterStyle.ListStyleType, "List-Style-Type" },
            {HtmlTextWriterStyle.Margin, "Margin" },
            {HtmlTextWriterStyle.MarginBottom, "Margin-Bottom" },
            {HtmlTextWriterStyle.MarginLeft, "Margin-Left" },
            {HtmlTextWriterStyle.MarginRight, "Margin-Right" },
            {HtmlTextWriterStyle.MarginTop, "Margin-Top" },
            {HtmlTextWriterStyle.Overflow, "Overflow" },
            {HtmlTextWriterStyle.OverflowX, "OverflowX" },
            {HtmlTextWriterStyle.OverflowY, "OverflowY" },
            {HtmlTextWriterStyle.Padding, "Padding" },
            {HtmlTextWriterStyle.PaddingBottom, "Padding-Bottom" },
            {HtmlTextWriterStyle.PaddingLeft, "Padding-Left" },
            {HtmlTextWriterStyle.PaddingRight, "Padding-Right" },
            {HtmlTextWriterStyle.PaddingTop, "Padding-Top" },
            {HtmlTextWriterStyle.Position, "Position" },
            {HtmlTextWriterStyle.TextAlign, "Text-Align" },
            {HtmlTextWriterStyle.TextDecoration, "Text-Decoration" },
            {HtmlTextWriterStyle.TextOverflow, "Text-Overflow" },
            {HtmlTextWriterStyle.Top, "Top" },
            {HtmlTextWriterStyle.VerticalAlign, "Vertical-Align" },
            {HtmlTextWriterStyle.Visibility, "Visibility" },
            {HtmlTextWriterStyle.WhiteSpace, "White-Space" },
            {HtmlTextWriterStyle.Width, "Width" },
            {HtmlTextWriterStyle.ZIndex, "ZIndex" },
        };
        public static string ToName(this HtmlTextWriterStyle attributeVal) => s_attributes[attributeVal];
    }
}
