//HintName: WebForms.Designer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tests
{
    [WebFormsCore.ViewPath(@"Example.aspx")]
    partial class PageTest
    {
        public global::WebFormsCore.UI.WebControls.TextBox tbUsername;
        public global::WebFormsCore.UI.WebControls.TextBox tbPassword;
        public global::WebFormsCore.UI.WebControls.Button btnLogin;

        protected override void FrameworkInitialized()
        {
            base.FrameworkInitialized();
            if (tbUsername == null) throw new System.InvalidOperationException("tbUsername is not added in the view");
            if (tbPassword == null) throw new System.InvalidOperationException("tbPassword is not added in the view");
            if (btnLogin == null) throw new System.InvalidOperationException("btnLogin is not added in the view");
        }
    }

    public partial class CompiledViews
    {
        [WebFormsCore.CompiledView(@"Example.aspx", "99A570CF9BDD7521886CED3F10087EFA")]
        public class PageTestView : PageTest
        {

        private string Test => "Test";
    private class Template_0 : global::WebFormsCore.UI.ITemplate
{
public WebFormsCore.IWebObjectActivator WebActivator;
public void InstantiateIn(global::WebFormsCore.UI.Control container_0)
{
container_0.AddParsedSubObject(WebActivator.CreateLiteral("Test"));
}
}


            protected override void FrameworkInitialize()
            {
                base.FrameworkInitialize();

this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
var @ctrl0 = WebActivator.CreateHtml("html");
this.AddParsedSubObject(@ctrl0);
@ctrl0.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
var @ctrl1 = WebActivator.CreateHtml("head");
@ctrl0.AddParsedSubObject(@ctrl1);
@ctrl1.AddParsedSubObject(WebActivator.CreateLiteral("\n    "));
var @ctrl2 = WebActivator.CreateHtml("title");
@ctrl1.AddParsedSubObject(@ctrl2);
@ctrl1.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
@ctrl0.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
var @ctrl3 = WebActivator.CreateHtml("body");
@ctrl0.AddParsedSubObject(@ctrl3);
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral("\n    "));
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral("\n\n    "));
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral( Test ));
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral("\n\n    "));
var @ctrl4 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.HtmlForm>();
@ctrl4.ID = "form1";
this.form1 = @ctrl4;
@ctrl3.AddParsedSubObject(@ctrl4);
@ctrl4.AddParsedSubObject(WebActivator.CreateLiteral("\n        "));
var @ctrl5 = WebActivator.CreateHtml("div");
@ctrl4.AddParsedSubObject(@ctrl5);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl6 = WebActivator.CreateControl<global::Tests.ControlTest<global::Tests.TestItem>>();
@ctrl5.AddParsedSubObject(@ctrl6);
@ctrl6.AddParsedSubObject(WebActivator.CreateLiteral("\n                "));
@ctrl6.Template = new Template_0() { WebActivator = WebActivator };
@ctrl6.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl7 = WebActivator.CreateHtml("br");
@ctrl5.AddParsedSubObject(@ctrl7);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl8 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.TextBox>();
@ctrl8.ID = "tbUsername";
this.tbUsername = @ctrl8;
@ctrl5.AddParsedSubObject(@ctrl8);
var @ctrl9 = WebActivator.CreateHtml("br");
@ctrl5.AddParsedSubObject(@ctrl9);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl10 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.TextBox>();
@ctrl10.ID = "tbPassword";
this.tbPassword = @ctrl10;
@ctrl5.AddParsedSubObject(@ctrl10);
var @ctrl11 = WebActivator.CreateHtml("br");
@ctrl5.AddParsedSubObject(@ctrl11);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl12 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.Button>();
@ctrl12.ID = "btnLogin";
((WebFormsCore.UI.IAttributeAccessor)@ctrl12).SetAttribute("click", "btnLogin_Click");
((WebFormsCore.UI.IAttributeAccessor)@ctrl12).SetAttribute("text", "Login");
this.btnLogin = @ctrl12;
@ctrl5.AddParsedSubObject(@ctrl12);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n        "));
@ctrl4.AddParsedSubObject(WebActivator.CreateLiteral("\n    "));
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
@ctrl0.AddParsedSubObject(WebActivator.CreateLiteral("\n"));

            }
        }
    }
}
namespace Tests
{
    [WebFormsCore.ViewPath(@"Example.ascx")]
    partial class ControlTest
    {
        public global::WebFormsCore.UI.WebControls.Literal litTest;
        public global::WebFormsCore.UI.WebControls.Button btnIncrement;

        protected override void FrameworkInitialized()
        {
            base.FrameworkInitialized();
            if (litTest == null) throw new System.InvalidOperationException("litTest is not added in the view");
            if (btnIncrement == null) throw new System.InvalidOperationException("btnIncrement is not added in the view");
        }
    }

    public partial class CompiledViews
    {
        [WebFormsCore.CompiledView(@"Example.ascx", "8720F74DA00151D9EEAE36F4E42E4C75")]
        public class ControlTestView : ControlTest
        {


            protected override void FrameworkInitialize()
            {
                base.FrameworkInitialize();

this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(WebActivator.CreateLiteral("\n\n"));
var @ctrl0 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.Literal>();
@ctrl0.ID = "litTest";
this.litTest = @ctrl0;
this.AddParsedSubObject(@ctrl0);
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
var @ctrl1 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.Button>();
@ctrl1.ID = "btnIncrement";
@ctrl1.Click += (sender, e) => { this.btnIncrement_OnClick(sender, e); return default(global::System.Threading.Tasks.ValueTask); };
this.btnIncrement = @ctrl1;
this.AddParsedSubObject(@ctrl1);
@ctrl1.AddParsedSubObject(WebActivator.CreateLiteral("Increment"));

            }
        }
    }
}