//HintName: WebForms.Designer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tests
{
    [WebFormsCore.ViewPath(@"Example.aspx")]
    partial class PageTest
    {
        public global::WebFormsCore.UI.WebControls.TextBox tbUsername;
        public global::WebFormsCore.UI.WebControls.TextBox tbPassword;
        public global::WebFormsCore.UI.WebControls.Button btnLogin;

        [WebFormsCore.CompiledView(@"Example.aspx", "862483CFEBAFE390C88C63B24275DDB7")]
        public class CompiledView : PageTest
        {

        private string Test => "Test";
    
            protected override void FrameworkInitialize()
            {
                base.FrameworkInitialize();
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
var @ctrl0 = WebActivator.CreateHtml("html");
@ctrl0.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
var @ctrl1 = WebActivator.CreateHtml("head");
@ctrl1.AddParsedSubObject(WebActivator.CreateLiteral("\n    "));
var @ctrl2 = WebActivator.CreateHtml("title");
@ctrl1.AddParsedSubObject(@ctrl2);
@ctrl1.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
@ctrl0.AddParsedSubObject(@ctrl1);
@ctrl0.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
var @ctrl3 = WebActivator.CreateHtml("body");
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral("\n    "));
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral("\n\n    "));
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral( Test ));
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral("\n\n    "));
var @ctrl4 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.HtmlForm>();
@ctrl4.ID = "form1";
this.form1 = @ctrl4;
@ctrl4.AddParsedSubObject(WebActivator.CreateLiteral("\n        "));
var @ctrl5 = WebActivator.CreateHtml("div");
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl6 = WebActivator.CreateControl<global::Tests.ControlTest>();
@ctrl5.AddParsedSubObject(@ctrl6);
var @ctrl7 = WebActivator.CreateHtml("br");
@ctrl5.AddParsedSubObject(@ctrl7);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl8 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.TextBox>();
@ctrl8.ID = "tbUsername";
this.tbUsername = @ctrl8;
@ctrl5.AddParsedSubObject(@ctrl8);
var @ctrl9 = WebActivator.CreateHtml("br");
@ctrl5.AddParsedSubObject(@ctrl9);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl10 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.TextBox>();
@ctrl10.ID = "tbPassword";
this.tbPassword = @ctrl10;
@ctrl5.AddParsedSubObject(@ctrl10);
var @ctrl11 = WebActivator.CreateHtml("br");
@ctrl5.AddParsedSubObject(@ctrl11);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n            "));
var @ctrl12 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.Button>();
@ctrl12.ID = "btnLogin";
@ctrl12.Attributes["click"] = "btnLogin_Click";
@ctrl12.Attributes["text"] = "Login";
this.btnLogin = @ctrl12;
@ctrl5.AddParsedSubObject(@ctrl12);
@ctrl5.AddParsedSubObject(WebActivator.CreateLiteral("\n        "));
@ctrl4.AddParsedSubObject(@ctrl5);
@ctrl4.AddParsedSubObject(WebActivator.CreateLiteral("\n    "));
@ctrl3.AddParsedSubObject(@ctrl4);
@ctrl3.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
@ctrl0.AddParsedSubObject(@ctrl3);
@ctrl0.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(@ctrl0);
            }
        }
    }
}
namespace Tests
{
    [WebFormsCore.ViewPath(@"Example.ascx")]
    partial class ControlTest
    {
        public global::WebFormsCore.UI.WebControls.Literal litTest;

        [WebFormsCore.CompiledView(@"Example.ascx", "013399AF623542E9BA50FC84B0741226")]
        public class CompiledView : ControlTest
        {

            protected override void FrameworkInitialize()
            {
                base.FrameworkInitialize();
this.AddParsedSubObject(WebActivator.CreateLiteral("\n"));
this.AddParsedSubObject(WebActivator.CreateLiteral("\n\n"));
var @ctrl0 = WebActivator.CreateControl<global::WebFormsCore.UI.WebControls.Literal>();
@ctrl0.ID = "litTest";
this.litTest = @ctrl0;
this.AddParsedSubObject(@ctrl0);
            }
        }
    }
}