//HintName: WebForms.ViewState.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Web;


namespace Tests
{
    public partial class Example
    {
		protected override void WriteViewState(IViewStateWriter writer)
        {
            base.WriteViewState(writer);
			writer.Write<string>(test);
        }

		protected override void ReadViewState(IViewStateReader reader)
        {
            base.ReadViewState(reader);
			test = reader.Read<string>();
        }
    }
}
