//HintName: WebForms.Designer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tests
{
    partial class Example
    {
        public global::System.Web.UI.WebControls.TextBox tbUsername;
        public global::System.Web.UI.WebControls.TextBox tbPassword;
        public global::System.Web.UI.WebControls.Button btnLogin;
    }
}