namespace WebFormsCore;

/// <summary>Specifies how ASP.NET generates the <see cref="P:WebFormsCore.UI.Control.ClientID" /> for a control that can be accessed in client script.</summary>
public enum ClientIDMode
{
    /// <summary>The control inherits the <see cref="T:WebFormsCore.ClientIDMode" /> setting of its <see cref="P:WebFormsCore.UI.Control.NamingContainer" /> control.</summary>
    Inherit,

    /// <summary>The <see cref="P:WebFormsCore.UI.Control.ClientID" /> value is generated by concatenating the <see cref="P:WebFormsCore.UI.Control.ID" /> values of each parent naming container with the <see cref="P:WebFormsCore.UI.Control.ID" /> value of the control. In data-binding scenarios where multiple instances of a control are rendered, an incrementing value is inserted in front of the control's <see cref="P:WebFormsCore.UI.Control.ID" /> value. Each segment is separated by an underscore character (_). This algorithm is the only one that was available in versions of ASP.NET earlier than ASP.NET 4.</summary>
    AutoID,

    /// <summary>This algorithm is used for controls that are in data-bound controls. The <see cref="P:System.Web.UI.Control.ClientID" /> value is generated by concatenating the <see cref="P:System.Web.UI.Control.ClientID" /> value of the parent naming container with the <see cref="P:System.Web.UI.Control.ID" /> value of the control. If the control is a data-bound control that generates multiple rows, the value of the data field specified in the <see cref="P:System.Web.UI.WebControls.IDataBoundListControl.ClientIDRowSuffix" /> property is added at the end. For the <see cref="T:System.Web.UI.WebControls.GridView" /> control, multiple data fields can be specified. If the <see cref="P:System.Web.UI.WebControls.IDataBoundListControl.ClientIDRowSuffix" /> property is blank, a sequential number is added at the end instead of a data field value. Each segment is separated by an underscore character (_).</summary>
    Predictable,

    /// <summary>The <see cref="P:WebFormsCore.UI.Control.ClientID" /> value is set to the value of the <see cref="P:WebFormsCore.UI.Control.ID" /> property. If the control is a naming container, the control is used as the top of the hierarchy of naming containers for any controls that it contains.</summary>
    Static,
}
